### ISSUE TITLE
plot(tuned.mint.splsda) 's legend blocks the plot.

### ISSUE THREAD

**Issue by aljabadi** [mixOmicsTeam/mixOmics#10]
Hi Florian,

Occasionally, when trying to visualise the tune function's output, an important part of the plot is hidden under the legend ( see attached). It would be nice if the legend was somehow outside the main plot.

![tune](https://user-images.githubusercontent.com/28503057/51724898-9c98b880-20b3-11e9-930c-cf15c37e7c0f.png)

**Comment by frohart** [comment]
Hi there,

This graph is indeed awful. It can be that awful if you're saving it in weird proportion. 
Anyway, I'm going to make that graph using ggplot, so it'll be prettier.
Just to be sure: the graph looks like it's from a call to plot() on a splsda object, not a mint.splsda, am I right?

**Comment by aljabadi** [comment]
This specific case was actually a mint.splsda object, and the output format/aspect ratio was rmarkdown's default. I think ggplot2 style could be a great idea. Because for some tutorials that I made I had to extend the grid far beyond to ensure the optimum point markers are well outside the legend box.

**Comment by frohart** [comment]
Not sure how it would work for you to install, but I've made the changes on the devel branch with commit 0e1590c. Let me know if you can install and if it works as you hoped

**Comment by aljabadi** [comment]
Perfect. Thanks.

**Comment by aljabadi** [comment]
I haven't had issues so I guess it's all fine.
