### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by marcelladane** [mixOmicsTeam/mixOmics#102]
Hello, I am trying to install the package in Rstudio in windows 10:
"BiocManager::install("mixOmicsTeam/mixOmics")
 Bioconductor version 3.9 (BiocManager 1.30.10), R 3.6.1 (2019-07-05)"

And I get this issue:
Error: Failed to install 'mixOmics' from GitHub:
  (converted from warning) installation of package ‘C:/Users/marcpe/AppData/Local/Temp/RtmpycKxSg/file3b2c589264a0/mixOmics_6.13.49.tar.gz’ had non-zero exit status

Can you help me with it?

I also tried to implement using  Linux subsystem and mobaxterm, believing it was some windows issue. But then it fail on loading once I start Rstudio. Saying the pkgInfo file is missing. 

Best regards
Marcela

**Comment by aljabadi** [comment]
Hi @marcelladane, 

Can you please update to the latest Bioconductor ( 3.11 - https://www.bioconductor.org/install/) and try again?

**Comment by marcelladane** [comment]
Hello, now it works for installation directly on RStudio.

But when I try to install using conda (to keep it in an environment and keep the correct version of all packages), I get 2 errors: 
1 - stringi is missing, although is clearly there and updated. 
2 - pkgInfo file missing.

Can you give me any insight?

**Comment by aljabadi** [comment]
@marcelladane I'm not too sure about this specific issue.  I'd look up for possible solutions such as [this thread](https://github.com/conda-forge/r-stringi-feedstock/issues/13) (also [this discussion](https://stackoverflow.com/questions/46735932/rstudio-how-to-get-stringi-package-installation-to-work-all-good-until-dyn-load) as it might be a dyn.load issue).  Please do let us know if and how it was fixed.

Best,
Al

**Comment by marcelladane** [comment]
I managed to fix it in a very strange way. 
I installed stringi again (although it was there) followed by update. Now it works, but only for the previous version of mixOmics.
Not the latest. Just so you know.

Thx for the help. =)
