### ISSUE TITLE
Cutoff in mixOmics::network

### ISSUE THREAD

**Issue by GSantpere** [mixOmicsTeam/mixOmics#106]
Hi,

I found some edges not appearing in the network produced by mixOmics::network when I did not specified a cutoff. Documentation sets cutoff=NULL by default, but the resulting network has established a cutoff in my case of ~0.44. Only when I set the cutoff at 0 I can retrieve all edges.

It is not clear to me from the documentation how this parameter is set internally when it is not specified.

Thanks in advance and congratulations for this package.

**Comment by Max-Bladen** [comment]
Tried reproducing this bug in a variety of ways to no issue. Due to the time that this was posted, I can assume that this bug was resolved some time in the past
