### ISSUE TITLE
Error in dimnames(x) <- dn :    length of 'dimnames' [1] not equal to array extent

### ISSUE THREAD

**Issue by nvanzuy** [mixOmicsTeam/mixOmics#109]
HI,

I am trying to run tune.splsda and tune.block.splsda.  I am getting an error after the progress bar has reached 100% for comp1:  Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent

my dimnames match the dim of my matrix.  The matrix does contain missing values but I have removed columns with all NA values if they exist.  

The matrix is large 68 rows by ~27K columns.  I am unable to share any data so cannot post a reproducible example.

I also receive these errors:

In addition: Warning messages:
1: In (apply(conf, 1, sum) - diag(conf))/summary(Y) :
  longer object length is not a multiple of shorter object length
2: In (apply(conf, 1, sum) - diag(conf))/summary(Y) :
  longer object length is not a multiple of shorter object length
3: In (apply(conf, 1, sum) - diag(conf))/summary(Y) :
  longer object length is not a multiple of shorter object length
4: In (apply(conf, 1, sum) - diag(conf))/summary(Y) :
  longer object length is not a multiple of shorter object length
5: In (apply(conf, 1, sum) - diag(conf))/summary(Y) :
  longer object length is not a multiple of shorter object length

Is there anything that I could check?

Thanks,
Natalie

**Comment by aljabadi** [comment]
Hi @nvanzuy,

Thanks for reporting this. Unfortunately, we are a small team and unable to go through all possible scenarios and therefore we need a reproducible example to resolve this. Please follow the steps in https://mixomics-users.discourse.group/t/reproducible-example-to-clarify-issues/470 to see whether you can reproduce it using mixOmics data, or a small subset of your own data which you can send to us along with the code as explained in the post.

Best,

Al

**Comment by nvanzuy** [comment]
Hi,

I know it is really difficult to help me without data so I have begun debugging myself.  I started with just one block as an example:  

Running tune.spslda I have found where the error is generated in the MCV.spls function on lines 621-625 (code is repeated for all options of BER or overall:

{
                conf = get.confusion_matrix(truth = factor(Y), predicted = x)
                browser()
                out = (apply(conf, 1, sum) - diag(conf)) / summary(Y)
            })

The problem was with the summary of Y it contains NA values and that produced the error In (apply(conf, 1, sum) - diag(conf))/summary(Y) :
  longer object length is not a multiple of shorter object length

Would changing the code to this be valid? 

{
                conf = get.confusion_matrix(truth = factor(Y), predicted = x)
                out = (apply(conf, 1, sum) - diag(conf)) / summary(na.omit(Y))
            })


It looks valid to me but wanted to check? I can submit a pull request.

Thanks,
Natalie

**Comment by aljabadi** [comment]
Hi @nvanzuy,

Thank you for updating us on the issue. Please note that in discriminant analyses (`(block.)(s)plsda`) `Y` cannot contain missing values as it will be treated as a distinct class which is not what we want. You can simply remove that (or those) sample(s) and continue with the analyses.

We will have a much more informative message for that case in the next release.

Best,

Al
