### ISSUE TITLE
No 3D Plot Available

### ISSUE THREAD

**Issue by jsgalan** [mixOmicsTeam/mixOmics#11]
Hi all,

I have been having problems with getting the 3D plot for either the PCA or the PLSDA Analysis.  

At first i was not aware that the package rgl, so i proceeded to install it in R. After, I realized that it needed xQuartz, which i proceeded to download as a tar.gz and via brew.

I have the current setup:

- Macbook Pro

![screen shot 2019-01-27 at 4 19 15 pm](https://user-images.githubusercontent.com/971958/51807027-57a98900-224f-11e9-9c58-cc0b64cc2651.png)

-R version 3.5.2 (2018-12-20) -- "Eggshell Igloo"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)

-> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rgl_0.99.16

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0              digest_0.6.18           later_0.7.5             mime_0.6                R6_2.3.0               
 [6] xtable_1.8-3            jsonlite_1.6            magrittr_1.5            miniUI_0.1.1.1          promises_1.0.1         
[11] webshot_0.5.1           tools_3.5.2             manipulateWidget_0.10.0 htmlwidgets_1.3         crosstalk_1.0.0        
[16] shiny_1.2.0             httpuv_1.4.5.1          xfun_0.4                compiler_3.5.2          htmltools_0.3.6

-xQuartz 2.7.11 (xorg-server 1.18.4)
 
If i check the display on the terminal i get the following info:

jsgalan-gray:lib jsgalan$ echo $DISPLAY
/private/tmp/com.apple.launchd.8XHZxzhZOo/org.macosforge.xquartz:0

I have tried to run rgl examples (basically the demo(rgl) and i get the following:
![screen shot 2019-01-27 at 4 21 32 pm](https://user-images.githubusercontent.com/971958/51807043-b1aa4e80-224f-11e9-8562-ed0c675fe557.png)
![screen shot 2019-01-27 at 4 21 42 pm](https://user-images.githubusercontent.com/971958/51807044-b4a53f00-224f-11e9-8c47-561324fb8a58.png)

Which crashes R and shows the following error:

![screen shot 2019-01-27 at 4 17 42 pm](https://user-images.githubusercontent.com/971958/51807016-32b51600-224f-11e9-86cd-8e98e5bdfe9e.png)

I am just wondering if:

1- anyone else has encountered/solved this issue (which is mostly rgl related) 
2- if there are other packages or options that could be passed to the mixomics library to get the 3D plots without using the rgl package.

Best

**Comment by frohart** [comment]
Hi jsgalan,

1- As you mentioned, this is obviously a rgl issue, and it seems related to your system/environment. I have seen a lot of rgl problems (which is a reason why rgl is not imported anymore), but I haven't seen this one before.
I'd say either your X11 hasn't been installed properly (when you do  `x11()` in R, does it open a new window? Can you plot anything in that window?) or your system is missing something (devtools, xcode, ...)
2- I'm afraid you need the rgl library to have 3D plots with mixOmics..

**Comment by aljabadi** [comment]
Hi jsgalan,
I hope Florian's response could help. I'm closing this issue but please do get in touch if the problem has persisted.
