### ISSUE TITLE
OPLS-DA

### ISSUE THREAD

**Issue by rhhu** [mixOmicsTeam/mixOmics#114]
Is it possible to implement OPLS-DA (orthogonal Partial least squares-discriminant analysis) in mixOmics? 

I like the nice output of mixOmics, but it doesn't have OPLS-DA compared to ropls.

**Comment by aljabadi** [comment]
Hi @rhhu,

We are working on a number of new implementations but `OPLS-DA` has not been on our radar yet. We always welcome and acknowledge contributions if you would like to submit pull requests regarding such feature(s) :)

**Comment by Max-Bladen** [comment]
Hi @aljabadi 

Are we intending on implementing OPLS-DA? If so, is this a priority?

**Comment by Max-Bladen** [comment]
Closing due to large requirements to implement this feature and PLS functions should be updated and refactored before expanded them. Additionally, this would only see limited use.
