### ISSUE TITLE
plotDiablo - group colours

### ISSUE THREAD

**Issue by chongchunwie** [mixOmicsTeam/mixOmics#119]
Just wondering how to change the colours of the group under plotDiablo. I have tried col.per.group and col, but to no avail.

**Comment by aljabadi** [comment]
Hi @chongchunwie,

Thanks for reporting this. I think I fixed it in my devel which will soon be available on all platforms. You can install using `BiocManager::install('aljabadi/mixOmics@devel')` . Following is an example:

``` r
data('breast.TCGA')
Y = breast.TCGA$data.train$subtype

data = list(mrna =  breast.TCGA$data.train$mrna,
mirna =  breast.TCGA$data.train$mirna, prot =  breast.TCGA$data.train$protein)

# set number of component per data set
ncomp = 3
# set number of variables to select, per component and per data set (arbitrarily set)
list.keepX = list(mrna = rep(20, 3), mirna = rep(10,3), prot = rep(10,3))

# DIABLO using a full design where every block is connected
BC.diablo = block.splsda(X = data, Y = Y, ncomp = ncomp, keepX = list.keepX, design = 'full')
## default col.per.group
plotDiablo(BC.diablo, ncomp = 1, legend = TRUE, col.per.group = NULL)
```

![](https://i.imgur.com/qJW2OYG.png)

``` r
## custom col.per.group
col.per.group <- viridisLite::viridis(3)
names(col.per.group) <- levels(Y)
plotDiablo(BC.diablo, ncomp = 1, legend = TRUE, col.per.group = col.per.group)
```

![](https://i.imgur.com/G5TOBgZ.png)

<sup>Created on 2021-01-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Christoab** [comment]
@aljabadi It seems like there is a mismatch between colors and group in the devel.

Version 6.15.26:
![image](https://user-images.githubusercontent.com/80312884/110435439-50ead280-80b3-11eb-923d-a1e0bd36b289.png)

Version 6.15.33:
![image](https://user-images.githubusercontent.com/80312884/110435461-57794a00-80b3-11eb-92f1-2e7f289e9cfd.png)

**Comment by SchererFIMM** [comment]
@aljabadi 
Hi, thank you so much for your excellent work and help but I have the same problem, that the coloring of the samples gets screwed up when applying the color.per.group. The ellipses are now in the right colour, but the samples are mixed up. I had installed the mixomics development version and ran:
col.per.group <- c("blue","red")
names(col.per.group) <- levels(Y)
plotDiablo(MyResult.diablo, ncomp = 1, legend = TRUE, col.per.group = col.per.group)

![Before](https://user-images.githubusercontent.com/65248888/114147646-948a6380-9921-11eb-84ec-435ccfcb4062.jpg)
![After](https://user-images.githubusercontent.com/65248888/114147842-c6032f00-9921-11eb-8bab-8faaa5f7162a.jpeg)

best,
Andreas

**Comment by aljabadi** [comment]
@SchererFIMM @Christoab thanks for pointing this out, not sure how I missed that obvious bug. This should work as expected now. Please follow the installation instruction above.

``` r
data('breast.TCGA')
Y = breast.TCGA$data.train$subtype

data = list(mrna =  breast.TCGA$data.train$mrna,
            mirna =  breast.TCGA$data.train$mirna, prot =  breast.TCGA$data.train$protein)

# set number of component per data set
ncomp = 3
# set number of variables to select, per component and per data set (arbitrarily set)
list.keepX = list(mrna = rep(20, 3), mirna = rep(10,3), prot = rep(10,3))

# DIABLO using a full design where every block is connected
BC.diablo = block.splsda(X = data, Y = Y, ncomp = ncomp, keepX = list.keepX, design = 'full')
## default col.per.group
plotDiablo(BC.diablo, ncomp = 1, legend = TRUE, col.per.group = NULL)
```

![](https://i.imgur.com/AkEZafV.png)

``` r

## custom col.per.group
col.per.group <- viridisLite::viridis(3)
names(col.per.group) <- levels(Y)
plotDiablo(BC.diablo, ncomp = 1, legend = TRUE, col.per.group = col.per.group)
```

![](https://i.imgur.com/HAUexh9.png)

<sup>Created on 2021-04-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by SchererFIMM** [comment]
Thank you so much for your great help, it works well for me now. 
Great toolbox!
