### ISSUE TITLE
Specify ylim when plotting perf

### ISSUE THREAD

**Issue by SamGG** [mixOmicsTeam/mixOmics#12]
Hi,

I would like to specify the range of performance plot. Setting ylim does not work. In fact the plot.perf calls internal_graphic.perf which computes the perf range on its own.

I will go to a workaround but it sounds good to set ylim in a next release.

Best.

**Comment by aljabadi** [comment]
Thanks for the suggestion. 
`perf` now supports `ylim` in _devel_ version. Please let me know if you run into issues.
Best
