### ISSUE TITLE
kernel.pca problem

### ISSUE THREAD

**Issue by NineFR09** [mixOmicsTeam/mixOmics#125]
Hi, 
I am currently trying to create a kernel.pca with a meta-kernel object (from combine.kernels()) using the latest version of mixKernel.

I am having some issue with this function when running the kernel.pca, I am getting the following error :
"**Error in names(per.var) <- paste("PC", 1:length(per.var), sep = "") : attempt to set an attribute on NULL**"
which when I then try to plot the PCA using the plotIndiv() gives me:
"**Error in round(inf, 2) : non-numeric argument to mathematical function**"

But when I try to run a pca with a normal pca() function using the meta.kernel$kernel it works (only for one dimension at a time).

What I also do not understand is that even when I try using the TARAoceans data provided from the online tutorial (http://mixomics.org/mixkernel/) and the exact same code I am getting the same error and cannot make a plot either.

Have anyone ever came accross this issue before?

**Comment by aljabadi** [comment]
Hi @NineFR09,

mixKernel is a separate package which depends on mixOmics. Please submit the issue to the corresponding repo https://forgemia.inra.fr/jerome.mariette/mixKernel.
