### ISSUE TITLE
mint.splsda variates not to have space in column names

### ISSUE THREAD

**Issue by aljabadi** [mixOmicsTeam/mixOmics#13]
Hi Florian,

Since some might want to use the outputs of mint.splsda for their own analyses, I think it is a good idea to replace space with an underscore in column names to avoid using backticks in ggplot2 - such as the last line below.

```
library(mixOmics)
data(stemcells)

# -- feature selection
res = mint.splsda(X = stemcells$gene, Y = stemcells$celltype, ncomp = 3, keepX = c(10, 5, 15),
                  study = stemcells$study)

variates = as.data.frame(res$variates$X)
ggplot(variates, aes(`comp 1`, `comp 2`)) + geom_point()
```

**Comment by frohart** [comment]
I deleted the space, to have a similar behavior as with other functions.  So it's now "comp1", "comp2", etc

03388bc
