### ISSUE TITLE
Biplot scaling issue

### ISSUE THREAD

**Issue by vincent-van-hoef** [mixOmicsTeam/mixOmics#132]
---------
🐞   **Describe the bug:**
First of all thanks for an amazing tool! One thing I noticed is that the scaling of the loadings when making a biplot can be quite a bit off if these loadings are not spread evenly around zero (which can be the case when imposing a correlation threshold). This seems to be because the denominator in the ratio defining the scaling factor is defined as the maximum of all loadings passing the correlation threshold. This inflates the scaling factor when the loadings are negatively skewed; resulting in a biplot where the majority of the space is taken up by the loadings.

------------
🔍 **reprex results from [reproducible example](https://mixomics-users.discourse.group/t/reproducible-example-to-clarify-issues/470) including sessioninfo():**
``` r
suppressMessages(library(mixOmics))
data("breast.TCGA")
X <- breast.TCGA$data.train$mrna
Y <- breast.TCGA$data.train$subtype
res <- plsda(X = X, Y = Y)
# Skew loadings a little bit...
res$loadings$X <- res$loadings$X - 0.07
biplot(res, cutoff = 0.8)
#> Warning: ggrepel: 150 unlabeled data points (too many overlaps). Consider
#> increasing max.overlaps
```

![](https://i.imgur.com/9IhfqCe.png)

<sup>Created on 2021-06-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

------------
🤔  **Expected behavior:**
A biplot where the var arrows are scaled to be roughly the same size as the area used for the scores.

------------
💡  **Possible solution:**
Divide the maximum of the scores by the maximum of the absolute loadings.

So from `scaler <- max(variates, na.rm = TRUE)/max(loadings, na.rm = TRUE)` to `scaler <- max(variates, na.rm = TRUE)/max(abs(loadings), na.rm = TRUE)` in biplot.R

**Comment by aljabadi** [comment]
Thanks, @vincent-van-hoef, for pointing out this oversight and this wonderful and complete issue :)  It is now fixed in the latest version.
