### ISSUE TITLE
Description of the roc.comp parameter in auroc

### ISSUE THREAD

**Issue by stanstrup** [mixOmicsTeam/mixOmics#135]
Hello,

at the risk of exposing my complete ignorance I want to ask if the description of the `roc.comp` parameter for the `auroc` function is not misleading?

The docs say that `roc.comp`:
>Specify the component (integer) for which the ROC will be plotted from the multivariate model, default to 1.

This suggest to me that somehow if I set `roc.comp = 2` the first component is ignored. That doesn't make much sense to me.
What would make sense to me was if  `roc.comp = 2` meant that the first two components will be used (also this is the only way it makes sense to me that higher `roc.comp` gives better results). That is also how it is described here ("The first AUROC includes 2 components only") http://mixomics.org/case-studies/splsda-srbct/.
So if I am correct about what it actually does I suggest re-wording the doc.

Perhaps to something like
_"Specify the number of components (integer) for which the ROC will be plotted from the multivariate model, default to 1."_

The title of the plots should probably then be changed from "ROC Curve Comp 2" to "ROC Curve, 2 Component(s)"

**Comment by aljabadi** [comment]
Hi @stanstrup,
Thanks for pointing this out. These will be reflected in the later versions.
