### ISSUE TITLE
cimDiablo trims values without any announcements

### ISSUE THREAD

**Issue by aljabadi** [mixOmicsTeam/mixOmics#136]
`cimDiablo` trims the values with absolute values greater than 2 (see https://github.com/mixOmicsTeam/mixOmics/blob/master/R/cimDiablo.R#L184-L185). The value of `2` also seems somewhat arbitrary. This is hard-coded and might be ill-advised at times. We can probably allow users to override this step. Or at least, we can let users know what is happening.

**Comment by mixOmicsTeam** [comment]
Agree this is somewhat arbitrary and not needed? Unless there is a wide range of values and they are not scaled before visualisation? I'd be keen to remove that threshold entirely, unless some examples on our data show this is not appropriate.

**Comment by aljabadi** [comment]
I think the reason @singha53 chose to do this was to stop a small set of values from hijacking the strong sides of the colour gradients (see below for a comparison & note that in extreme cases most of the image could be white-ish). But as I said, we could possibly be a bit more careful with our definition of an outlier in the visualisations.

``` r
data(nutrimouse)
Y = nutrimouse$diet
data = list(gene = nutrimouse$gene, lipid = nutrimouse$lipid)

nutrimouse.sgccda <- block.splsda(X = data,
                                  Y = Y,
                                  design = "full",
                                  keepX = list(gene = c(10,10), lipid = c(15,15)),
                                  ncomp = 2,
                                  scheme = "centroid")
## default trims
cimDiablo(nutrimouse.sgccda, comp = c(1,2))
```

![image](https://user-images.githubusercontent.com/28503057/125745336-e6c98035-b8fe-4df5-b050-9356c46a4350.png)
```r
## do not trim values
cimDiablo(nutrimouse.sgccda, comp = c(1,2), trim = FALSE)
```
![image](https://user-images.githubusercontent.com/28503057/125745355-920bda1c-e518-4b0c-9429-d38a5515553b.png)

<sup>Created on 2021-07-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by Max-Bladen** [comment]
This adjustment was implemented and is currently functional. Closing post now
