### ISSUE TITLE
feature request: make plot call in network function optional

### ISSUE THREAD

**Issue by wgervasio** [mixOmicsTeam/mixOmics#145]
**Description of what the problem is. Ex. I'm always frustrated when [...]**
Whenever I want to work on the network graphs, R plots it automatically. This can be troublesome when displaying further processed results in Shiny as an example.

**Describe the solution you'd like**
add a boolean to the network args to turn off plotting

**Comment by Max-Bladen** [comment]
Hi @wgervasio,

I've implemented your requested enhancement. You can access it using the following commands in R:

`devtools::install_github("mixOmicsTeam/mixOmics", ref = github_pull("201"))`

Please let me know if you notice any issues

**Comment by wgervasio** [comment]
Works fine on my end! It solves an issue I had with a Shiny app for quite a while :)
