### ISSUE TITLE
tune.spls X changes in latest update affecting existing analysis

### ISSUE THREAD

**Issue by CatrionaJones** [mixOmicsTeam/mixOmics#149]
**Is your feature request related to a problem? Please describe.**
 
I don't want to have to manually remove 11,000 columns from my dataset to make the model work, I am running an sPLS on my data so that it selects X variables for me.

**Describe the solution you'd like**

**Describe alternatives you've considered**
 
The whole point of running the sPLS is so I don't have to manually reduce the number of X variables, I want the model to do it for me. 

**Additional context**

**Comment by aljabadi** [comment]
Hi @CatrionaJones,
Can you please expand on what happens with the latest tune.spls function compared to the old one? 
Thanks

Al
