### ISSUE TITLE
plotArrow Error: Aesthetics must be either length 1 or the same as the data 

### ISSUE THREAD

**Issue by aljabadi** [mixOmicsTeam/mixOmics#150]
See https://mixomics-users.discourse.group/t/error-in-plotarrow-of-splsda/689

**Comment by eacton** [comment]
Hi! I am also having this error with plotArrow for splsda objects. Just wondering if there have been any fixes or work-arounds yet. Thanks!

**Comment by shaman-narayanasamy** [comment]
Hi, 

I am having an issue with this plot as well. Looking forward to the fixes.

For more information/context, I am following the [MINT case study](http://mixomics.org/mixmint/stemcells-example/). Here are more details of the errors received when executing `plotArrow(mint.splsda.res)`:

```
Error: Aesthetics must be either length 1 or the same as the data (125): x, y, xend and yend Run `rlang::last_error()` to see where the error occurred.
```

Executing `rlang::last_error()` yields the following:
```
<error/rlang_error>
Aesthetics must be either length 1 or the same as the data (125): x, y, xend and yend
Backtrace:
 1. (function (x, ...) ...
 2. ggplot2:::print.ggplot(x)
 4. ggplot2:::ggplot_build.ggplot(x)
 5. ggplot2:::by_layer(function(l, d) l$compute_aesthetics(d, plot))
 6. ggplot2:::f(l = layers[[i]], d = data[[i]])
 7. l$compute_aesthetics(d, plot)
 8. ggplot2:::f(..., self = self)
 9. ggplot2:::check_aesthetics(evaled, n)
```
