### ISSUE TITLE
leave one out validation does not return choice.ncomp for tune.splsda

### ISSUE THREAD

**Issue by tyronechen** [mixOmicsTeam/mixOmics#151]
Please follow **all the steps** described at https://mixomics-users.discourse.group/t/reproducible-example-to-clarify-issues/470 and next fill in the items below:

------------
🐞   **Describe the bug:**

When running `tune.splsda` following the example in [http://mixomics.org/case-studies/splsda-srbct/](http://mixomics.org/case-studies/splsda-srbct/), replacing `Mfold` with `loo` results in empty `tune.splsda.srbct$choice.ncomp` variable

------------
🔍 **reprex results from [reproducible example](https://mixomics-users.discourse.group/t/reproducible-example-to-clarify-issues/470) including sessioninfo():**

```
...
> tune.splsda.srbct <- tune.splsda(X, Y, ncomp = 6, validation = 'loo', folds = 5,
                           progressBar = TRUE, dist = 'max.dist', measure = "BER",
                          test.keepX = list.keepX, nrepeat = 10, cpus = 2)
> tune.splsda.srbct$choice.keepX
comp1 comp2 comp3 comp4 comp5 comp6
   70   290     2     1     1     1
> tune.splsda.srbct$choice.ncomp
$ncomp
NULL

$values
NULL

> sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS/LAPACK: /Users/tche0054/.conda/envs/mix/lib/libopenblasp-r0.3.15.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] BiocParallel_1.24.1 mixOmics_6.17.27    ggplot2_3.3.3
[4] lattice_0.20-44     MASS_7.3-54
```
------------
🤔  **Expected behavior:**

Expected `loo` to return the same output variables as tutorial with `Mfold`:

```
tune.splsda.srbct <- tune.splsda(X, Y, ncomp = 6, validation = 'Mfold', folds = 5,
                           progressBar = TRUE, dist = 'max.dist', measure = "BER",
                          test.keepX = list.keepX, nrepeat = 10, cpus = 2)
...
> tune.splsda.srbct$choice.ncomp
$ncomp
[1] 3

$values
            comp1     comp2      comp3      comp4      comp5      comp6
nrep.1  0.5254529 0.1958333 0.00000000 0.01086957 0.01086957 0.00000000
...
```

------------
💡  **Possible solution:**

In `tune.splsda`, `ncomp_opt` is set to `NULL` if `nrepeat == 1` (which is required by `loo` cross validation)

[Line 553 of `tune.splsda.R`](https://github.com/mixOmicsTeam/mixOmics/blob/6bdb5cbcd7ef33108d878d4f017089837dbf4e9b/R/tune.splsda.R#L553)

```
        else {
            ncomp_opt = error.keepX = NULL
        }
```

**Comment by aljabadi** [comment]
Thanks for the awesome description @tyronechen.

We really wish we could provide a measure of optimality when the cross-validation is not repeated more than twice. As you can see, we use the [`t.test.process` function](https://github.com/mixOmicsTeam/mixOmics/blob/6bdb5cbcd7ef33108d878d4f017089837dbf4e9b/R/tune.splsda.R#L534) to tune the number of components and it runs a [t.test](https://github.com/mixOmicsTeam/mixOmics/blob/6bdb5cbcd7ef33108d878d4f017089837dbf4e9b/R/t.test.process.R#L42-L43) which by definition requires vectors of values. That is why we only output that if the cross-validation is repeated more than 2 times. It might be useful to output the 'optimal' ncomp only based on scalar values, However, we're aware that this might be too risky of an 'automated recommendation' given that we're simultaneously optimising the number of components as well as the number of features to select. I'd be happy to hear your thoughts on this.

**Comment by tyronechen** [comment]
> We really wish we could provide a measure of optimality when the cross-validation is not repeated more than twice. As you can see, we use the t.test.process function to tune the number of components and it runs a t.test which by definition requires vectors of values. That is why we only output that if the cross-validation is repeated more than 2 times.

Thanks for the information @aljabadi , i overlooked the `vector` part and it makes sense.

> It might be useful to output the 'optimal' ncomp only based on scalar values, However, we're aware that this might be too risky of an 'automated recommendation' given that we're simultaneously optimising the number of components as well as the number of features to select. I'd be happy to hear your thoughts on this.

Would raising a warning be a useful feature in the next release? Eg it could either raise a warning when `loo` is selected or autoselect a scalar value and raise a warning.
