### ISSUE TITLE
consistency in plotLoadings outputs

### ISSUE THREAD

**Issue by htudela** [mixOmicsTeam/mixOmics#155]
Hi,
I would like to ask why does the `plotLoadings` function does not output the same data depending on the input object. `plotLoadings` outputs the coordinates , the importance and other variables where the rows are named based on the input data when using a `mixo_plsda` object, whereas when using a `mixo_pls` object the dataframe only output the ordered importances **without** the variable names, which is not very useful.
Would it be possible to fix this in future releases ? Is there any other way to have this dataframe with the variable names ?
Thanks.

**Comment by htudela** [comment]
I managed to get what I wanted using the `selectVar` function, but still I think that standardizing the outputs of `plotLoadings` makes sense.

**Comment by aljabadi** [comment]
Hi @htudela,

Thanks for opening this issue. We had in fact noticed this in the past and have that on our list. for future releases
