### ISSUE TITLE
mixOmics  6.17.26 build failing on Bioconductor

### ISSUE THREAD

**Issue by aljabadi** [mixOmicsTeam/mixOmics#157]
* see http://bioconductor.org/checkResults/devel/bioc-LATEST/mixOmics/

* see https://github.com/mixOmicsTeam/mixOmics/runs/3753496049?check_suite_focus=true

**Comment by zeehio** [comment]
The error building the package  is the issue with is() from #162

**Comment by Max-Bladen** [comment]
Hi @aljabadi 

I believe this was addressed some time ago. Just checking that this issue is okay to be closed?
