### ISSUE TITLE
BPPARAM() is giving an error when trying to use it for tuning spca (macOS Catalina)

### ISSUE THREAD

**Issue by mariamsm1** [mixOmicsTeam/mixOmics#158]
I am trying to use BPPARAM() option to speed up the computation for tuning spca. I am working on "Gastrulation" dataset which is a pretty big dataset with some missing values (NA).
I tried first to run the code without BPPARAM argument as the following:

**grid.keepX <- c(seq(10, 100, 5))
set.seed(30)
tune.spca.rna <- tune.spca(X, ncomp = 3,
                              folds = 20,
                              test.keepX = grid.keepX, nrepeat = 10)**

This is however taking so much time and it never finishes.

Then I tried BPPARAM option as the following:

**BPPARAM <- BiocParallel::MulticoreParam(workers = parallel::detectCores()-1)
tune.spca.rna <- tune.spca(X, ncomp = 3,
                              folds = 20,
                              test.keepX = grid.keepX, nrepeat = 10, BPPARAM = BPPARAM)**

This generated the following error:
**Error in base::options() :
Value of SET_STRING_ELT() must be a ‘CHARSXP’ not a ‘NULL**

P.S. I am using mixOmics (v6.17.29), Rstudio (v2021.09.0+351), R (v4.1.1).

Thank you.

**Comment by aljabadi** [comment]
Hi @mariamsm1,

We pushed a suite of changes to `6.18.1` and I have no issue running your example on it. Can you please update to the latest Bioc version and try again?

**Comment by mariamsm1** [comment]
Thank you @aljabadi it is working now!
