### ISSUE TITLE
memory issue when applying PCA/NIPALS

### ISSUE THREAD

**Issue by phauchamps** [mixOmicsTeam/mixOmics#18]
Hi dear MixOmics community,
Using pca with NIPALS algo (X has NA values!), I get a memory issue. I must say I have a X matrix with 78,000 variables (and 700 observations). 
The call to mixOmics::pca() gives the following message : 
Error: cannot allocate vector of size 45.9 Gb
Is there a way to tune the method to have it use (much) less memory ? 
Thanks,
Philippe

**Comment by aljabadi** [comment]
Hi @phauchamps, 
Not at the moment, unfortunately.  The workarounds can be:
1. Run it on a high-performance computing cluster which gives you more resources.
2. keep a subset of highly variable features (probably around 10000 in your case) and then perform `pca`. For example:
```
library(mixOmics)
## keeping top 50 features
topN=50
## toy matrix with NA's
mat <- matrix(sample(c(1:100,NA), 1000, replace = TRUE), nrow = 10, dimnames = list(paste0("sample-",1:10), paste0("feature-",1:100)))
## order features based on variance
mat <- mat[,order(colVars(mat, na.rm = TRUE), decreasing = TRUE)]
## subset
mat <- mat[,1:topN]
## perform pca
pca.res <- pca(mat)
```

Hope it helps.
