### ISSUE TITLE
MINT-PLS -> Not finished :'(

### ISSUE THREAD

**Issue by JeremyTournayre** [mixOmicsTeam/mixOmics#19]
Hello,
 
I am a PhD student at the end of my thesis, in order to make an article I am using your "MINT-PLS" tool on my data from several experiments using a Y variable as a continuous variable: the weight. The function mint.pls works well and allows me to make a plot of my samples with the function plotIndiv. However, I would like to be able to do everything you do on http://mixomics.org/mixmint/stemcells-example/ as testing the performance of the model but with a continuous variable. I also want to use the predict function on a test dataset as explained here: http://mixomics.org/methods/pls-da/. Unfortunately when I want to use the function perf.mint.pls I get this error message telling me that the function is not ready yet:
Error in perf.mint.pls (res, validation = "Mfold", folds = 5, progressBar = FALSE,:
  Yet to be implemented
Do you know when it will be ready please? The predict function does not work too:
Error in predict.mixo_pls (res, methyl_data, dist = "max.dist"):
  'study.test' is missing
 
If these features are not ready soon, do you know another way to test the performance and use the predict function on a model from the mint.pls function with a continuous variable in Y?
 
Regards,
Jérémy
-- 
UNH, UMR1019, Equipe iMPROVINg
INRA, Centre de Clermont Ferrand-Theix
Site de Theix
63122 Saint Genès Champanelle
Tel: 04 73 62 49 39

**Comment by JeremyTournayre** [comment]
Hello,

I have another problem : the nrepeat and the  the folds argument for the perf function for the Mint-PLS dont work. Maybe it's normal for these options to be disabled?

"nrepeat
Number of times the Cross-Validation process is repeated. This is an important argument to ensure the estimation of the performance to be as accurate as possible."

Regards,
Jérémy

**Comment by aljabadi** [comment]
Hi Jeremy,
As mentioned in the `perf `documentation, the function only supports objects of classes: "pls", "plsda", "spls", "splsda" or "mint.splsda". Therefore, it cannot be applied to `mint.spls` class.

**Comment by mixOmicsTeam** [comment]
HI Jeremy,
to complete @ajabadi's answer, the reason why there is no `nrepeat` argument is because MINT is doing a leave-one-group-out cross-validation (i.e. we remove one study and test/predict on that study). See details in our [MINT paper](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-017-1553-8), and also in the [mixOmics paper](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005752). We hope that helps!
