### ISSUE TITLE
Out of date information and source code in online vignette

### ISSUE THREAD

**Issue by jamesjiadazhan** [mixOmicsTeam/mixOmics#230]
Please follow **all the steps** described at https://mixomics-users.discourse.group/t/reproducible-example-to-clarify-issues/470 and next fill in the items below:

------------
🐞   **Describe the bug:**

I tried to tune the parameter for my SPLS models, but it did not work at all due to the following errors:

> plot(perf.pls$Q2.total)
Error in plot.window(...) : need finite 'xlim' values
In addition: Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf
3: In min(x) : no non-missing arguments to min; returning Inf
4: In max(x) : no non-missing arguments to max; returning -Inf

This error even happened when I used the following example codes provided in the vignette:

> data(liver.toxicity)
> X <- liver.toxicity$gene
> Y <- liver.toxicity$clinic
> 
> result.spls <- spls(X, Y, ncomp = 5, mode = "regression")
> perf.pls <- perf(result.spls, validation = 'Mfold', folds = 7,  nrepeat = 10, progressBar = TRUE)
> plot(perf.pls$Q2.total)

Error in plot.window(...) : need finite 'xlim' values
In addition: Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf
3: In min(x) : no non-missing arguments to min; returning Inf
4: In max(x) : no non-missing arguments to max; returning -Inf

When I tested what was in the perf.pls$Q2.total, I found nothing, as shown below:
> perf.pls$Q2.total
NULL

------------
🔍 **reprex results from [reproducible example](https://mixomics-users.discourse.group/t/reproducible-example-to-clarify-issues/470) including sessioninfo():**

------------
🤔  **Expected behavior:**

I hope the team can fix this bug. It is frustrating that even the example codes are not working.

------------
💡  **Possible solution:**

**Comment by Max-Bladen** [comment]
Hi @jamesjiadazhan,

Some of the information in the vignette is really quite old. I'd recommend using the website. It contains all the info the vignette does and more. Also, I rewrote the entire site late last year so its fully up to date

Cheers for the heads up
