### ISSUE TITLE
plotLoadings issue

### ISSUE THREAD

**Issue by aldosc** [mixOmicsTeam/mixOmics#232]
Dear MixOmics team,

I have completed an analysis by using DIABLO. Two blocks, mRNA and protein. When I tried to plot the loadings and their contributions, only one block information (mRNA) is being displayed, gene names and loadings bars. However,  for the protein block, only gene names are plotted. Trying to understand what is going on, I found out that there are differences between the information being used for plotting each block. This is how it looks for the protein block (attached snapshot), so the color is set to white and the group to tie. Any help would be appreciated. 

Thanks!
![Screenshot_20220827-003728_Outlook](https://user-images.githubusercontent.com/40887687/187003415-1755fc25-a228-49a6-b356-a22a7ac0135e.jpg)

**Comment by Max-Bladen** [comment]
Hi @aldosc 

 I don't quite understand the issue you are encountering based off your description. You need to attach a reproducible example as well as the plots you are referring to. Refer to the templates available in the Issues page. The screenshot you've attached doesn't help me diagnose your issue at all unfortunately.

I am unable to reproduce only one set of loadings being shown. When I use the function, it produces the below plot. Are you using the `block` parameter at all?

``` r
data(breast.TCGA)
X <- list(mRNA = breast.TCGA$data.train$mrna[,1:10],
          proteomics = breast.TCGA$data.train$protein[,1:10])
Y <- breast.TCGA$data.train$subtype

model <- block.splsda(X, Y)

plotLoadings(model, contrib = "max", method = "median")
```

![](https://i.imgur.com/bh2bLRA.png)

<sup>Created on 2022-08-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by aldosc** [comment]
Hi Max,

Thanks for your rapid reply. 
I think I know what's going on with the plots. 
When you have two samples/conditions contributing equally to the same factor, that's flagged as a tie. Looking at the default options of plotLoadings, color for ties is white. So, the bar plot is there, just unable to see it because of its color and the white background. When I changed color ties to black, then I can see the plot.

Best,

Aldo
