### ISSUE TITLE
Integration of multiomics data

### ISSUE THREAD

**Issue by mohamadysn** [mixOmicsTeam/mixOmics#254]
Hello,

I work with three types of omics data (transcriptomics (RNA-seq or scRNA-seq), methylome (EM-seq) and epigenomics (Chip-seq) in Alzheimer’s disease. Can I use Mixomics to integrate these three types together? If so, how? and what should I do with this data before using mixOmics?

Thank you in advance

**Comment by Max-Bladen** [comment]
Hi @mohamadysn 



Unfortunately, your question is very bare-bones, making it difficult to answer properly. The short answer is yes, you can use `mixOmics`. By the sounds of it, you have a categorical response variable (presence of Alzheimer's), so you would want to look up the DIABLO method. I can't tell you exactly what you need to do as you haven't provided any context.

Also, I'd recommend looking at the website. I've filled it with tons of info on [Selecting a method](http://mixomics.org/methods/selecting-your-method/). There are also pages corresponding to [basic usage](http://mixomics.org/mixdiablo/) and [specific case studies](http://mixomics.org/mixdiablo/diablo-tcga-case-study/) for the DIABLO method (assuming that this is appropriate for your use).
