### ISSUE TITLE
Error in if (is.unsorted(roc$specificities)) { :  missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by shaman-narayanasamy** [mixOmicsTeam/mixOmics#255]
Dear developer/maintainers,

I am attempting to run MINT `plsda` on my transcriptomics data. My data has **~25000 features (genes), 984 samples, derived from 12 datasets, representing three outcomes/classes**. I am facing an error when I try to include AUC for my performance evaluation. Code here:

``` r
reprex::reprex()
mint.plsda.res.perf = mint.plsda(X = X, Y = Y, study = study, ncomp = 10) 

set.seed(2543) 

perf.mint.plsda <- 
  perf(mint.plsda.res.perf, 
       validation = "Mfold", 
       folds = 5,  
       nrepeat = 2,
       progressBar = FALSE, 
       auc = TRUE)
```

Error here: 
```
Error in if (is.unsorted(roc$specificities)) { : 
missing value where TRUE/FALSE needed
```

When I choose not to use AUC, i.e. `auc = FALSE`, it works without any issue, which means that my data is fine, but somehow does not allow for AUC performance evaluation. May I know if there is something else I should check to debug.

Looking forward to your response. 

Best regards,
Shaman

**Comment by Max-Bladen** [comment]
I am unable to reproduce your issue at all - but my guess is that this is due to a rogue `NA` within `roc$specificities`. Why there is an NA there, I can't be sure. If you provide your email, I'll reach out to you and we can sort this out - I may need your data to resolve this issue

**Comment by shaman-narayanasamy** [comment]
Hi @Max-Bladen, 

Apologies for the delayed response. I am happy to provide you with the data. My e-mail: shaman.narayanasamy@uni.lu

Cheers,
Shaman

**Comment by evaham1** [comment]
Hi @shaman-narayanasamy, sorry for the delay but we have now changed over mixOmics maintainers, could you please let me know if you are still encountering this issue and would like me to follow up? Thanks!

**Comment by shaman-narayanasamy** [comment]
Hi @evaham1,

Thank you for reaching out! My apologies for the delay and my bad as I actually did not send the dataset over to @Max-Bladen. I am closing the issue as I am now currently working on the dataset in question.

I will contact you in the future if I come across this issue again. 

Cheers,
Shaman
