### ISSUE TITLE
plot.tune's X axis to have a consistent grid

### ISSUE THREAD

**Issue by aljabadi** [mixOmicsTeam/mixOmics#26]
In the following `plot` method for `tune` object, the `X` axis seems to have a log scale, while often people use a linear grid with fine tuning.  @mixOmicsTeam do you think we can shift it back to linear scale?.

```
data(breast.tumors)
X = breast.tumors$gene.exp
Y = as.factor(breast.tumors$sample$treatment)
tune = tune.splsda(X, Y, ncomp = 2, test.keepX = c(5, 10, 40),
                   folds = 10, dist = "max.dist", nrepeat = 5, progressBar = TRUE)

plot(tune)
```

**Comment by mixOmicsTeam** [comment]
closing since the spacing is deliberate to focus on fewer variables.
