### ISSUE TITLE
Is integration of single-omics multivariate data right with mixOmics?

### ISSUE THREAD

**Issue by Biojenifer** [mixOmicsTeam/mixOmics#272]
Hi!

I was wondering if mixOmics is useful to integrate different types of genomics data. In my case, I would like to integrate SNVs, CNAs and HLA haplotypes from the same cohort of samples. SNVs and CNAs share the same type of features, which are genes, but the other data matrix refers to other type of features, which are HLA alleles. 

As all of these data are derived from the same biological source (DNA), I am aware that this is a single-omics multivariate analysis and not a multi-omics analysis; so I was wondering if it would still be right to use mixOmics to integrate my data.

Thanks!

**Comment by mixOmicsTeam** [comment]
Hello,
Yes you can divide up your data depending on what they represent, especially if the scale / characteristics of the data are different (as it happens for example with total RNA, partitioned into miRNA, lncRNA etc).
Note though that those tools may not be fully efficient on variants and SNP data.

This data analysis question should be sent on our discussion forum (https://mixomics-users.discourse.group/) , rather that the GitHub issues.

Regards,
Kim-Anh
