### ISSUE TITLE
how to perform O2PLS?

### ISSUE THREAD

**Issue by wangpeng407** [mixOmicsTeam/mixOmics#290]
I note that there only have ```psl``` or ```spls``` function to run regression analysis. Now I want to ask how to perform O2PLS using mixOmics package?

**Comment by evaham1** [comment]
Hi @wangpeng407 please use our mixOmics discussion forum for any questions about analysis (we only use Github issues for bug reports), you might find other people have posted a similar question to yours on there - https://mixomics-users.discourse.group/
