### ISSUE TITLE
N-integration sample integration doubt

### ISSUE THREAD

**Issue by yitengfei120011** [mixOmicsTeam/mixOmics#306]
Hi, I noticed that N-integration can integrate multi-omics data, but there are questions about the samples in N-integration method. Are the N-integration samples exactly the same in each omics, or do they have the same sample type?

**Comment by evaham1** [comment]
Hi @yitengfei120011 please use our mixOmics discussion forum for any questions about analysis (we only use Github issues for bug reports), you might find other people have posted a similar question to yours on there - https://mixomics-users.discourse.group/
