### ISSUE TITLE
Extraction of dendrogram feature order

### ISSUE THREAD

**Issue by tkapello** [mixOmicsTeam/mixOmics#308]
Dear mixOmics team,

 I have run `cim()` and would like to extract the order of the features on the heatmap. I tried to re-run the function but could not succeed. Could you help?

Thank you in advance.

**Comment by LafontRapnouilTristan** [comment]
Hi,

I've done it myself by assigning the output of `cimDiablo`  to an object `sayed_object`.
You can then access row and column order (which are clustered) via `sayed_object$row.names` and `sayed_object$col.names`. 
Hope it helped,
Cheers

**Comment by evaham1** [comment]
Hello! I can confirm that @LafontRapnouilTristan's approach works to extract the row and column order from the output of `cim()`, hope that has helped!
