### ISSUE TITLE
Mixomics on R

### ISSUE THREAD

**Issue by sa825** [mixOmicsTeam/mixOmics#31]
Hi I have downloaded R version 3.5.2 and since tried to install the mixomics package using the function: install.packages("mixOmics")

In response I get this error: "Warning in install.packages : package ‘mixOmics’ is not available (for R version 3.5.2)"

Do I need a older version of R or what do I do?

Thanks,

Shimon

**Comment by aljabadi** [comment]
Hi @sa825,
mixOmics is now on [`Bioconductor`](http://bioconductor.org/packages/release/bioc/html/mixOmics.html) and you can install it using [these guidelines](https://github.com/mixOmicsTeam/mixOmics/blob/master/README.md#latest-bioconductor-release). Please consider updating to the [latest R version](https://cran.r-project.org/) to avoid Bioconductor warning messages. 
In short, run the following code to install it after updating R:
```
## install BiocManager if not installed
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
## install mixOmics
BiocManager::install('mixOmics')
```

Please let me know if you have any issues.

**Comment by sa825** [comment]
Hi Ajabadi, 

I have been able to install it, thank you and have since tried to do sPLSDA following the steps of the case study on the website (http://mixomics.org/case-studies/splsda-srbct/). However, I can't seem to do it right as I keep getting the error: "Error X must be a numeric value"? I 'm not really sure what to do at this point. Here's the code of the issue:

> library(mixOmics)
> setwd("C:/Users/sa825/OneDrive - University of Leicester/PhD/BIOSTAT/4. Sparse PLSDA (sPLSDA)/Figuring Leong out")
> mydata <- read.csv("LRARawData.csv", header = TRUE)
> X = mydata
> dim(X)
[1]   81 1041
> mydata2 <- read.csv("LRAAvD.csv", header = TRUE)
> Y = mydata2
> summary(Y)
 Description
 A:41       
 D:40       
> pca.mydata = pca(X, ncomp = 10, center = TRUE, scale = TRUE)
Error: 'X' must be a numeric matrix.
> View(X)

Thanks,

Shimon

**Comment by aljabadi** [comment]
Hi,
It could be because the csv file is read as a character and/or you also have rownames in CSV file that you haven't specified. Look up `read.table` function and see if `row.names = index_of_rowname_column` is appropriate:
```
X <- read.table("LRARawData.csv", sep = ",", header = TRUE, 

row.names = 1) ## only if you have rownames in column 1 in csv file
```
Eventually, you can run `pca` if the following code returns `TRUE` for all

```
is(X, matrix)
is(X, numeric)
```
if it doesn't, try the following before `pca`:
```
X <- as.matrix(mydata)
X <- as.numeric(mydata)
```
Hope it helps.

**Comment by sa825** [comment]
Hi,

Thank you for your reply. I have now been able to read my data. However, when I try to do plot (perf.splasda...) it doesn't work:

plot(perf.plsda.LRARawData, col = color.mixo(5:7), sd = TRUE, legend.position = "horizontal")
Error in plot.window(...) : need finite 'xlim' values
In addition: Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf

This same error comes up when I do the SRBCT Case Study on the mixOmics website (http://mixomics.org/methods/pls-da/) :

plot(perf.plsda.srbct, col = color.mixo(5:7), sd = TRUE, legend.position = "horizontal")
Error in plot.window(...) : need finite 'xlim' values
In addition: Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf

Furthermore, when I try to use the tune.plsda function, I get another error:

> tune.splsda.LRARawData <- tune.splsda(X, Y, ncomp = 6, validation = 'Mfold', folds = 5, progressBar = TRUE, dist = 'max.dist', measure = "BER", test.keepX = list.keepX, nrepeat = 10, cpus = 2):
Error in loadNamespace(name) : there is no package called ‘snow’

Apologies if this is a lot, I just don't know what to do next. Looking forward to your reply.

Thanks,

Shimon

**Comment by aljabadi** [comment]
You can resolve this using the instructions in https://github.com/mixOmicsTeam/mixOmics/issues/27. The `cpu` argument should be used only if the script is being run on a SNOW cluster.
