### ISSUE TITLE
tranform before PCA?

### ISSUE THREAD

**Issue by marwa38** [mixOmicsTeam/mixOmics#312]
Hi team 
Do you recommend to run log tranform the data before visualising using PCA? or even PLSDA? knowing that the data is normalised. 
Especially when the data is not meeting the parametric assumptions that PCA requires. 

I ran permanova on the results and I got no significant difference between male and female groups although PLSDA showed seperation?
![image](https://github.com/user-attachments/assets/20116272-36d8-44f1-bf2f-b1126a454182)

Please let me know 
Marwa

**Comment by evaham1** [comment]
Hi @marwa38 please use our mixOmics discussion forum for any questions about analysis (we only use Github issues for bug reports), you might find other people have posted a similar question to yours on there - https://mixomics-users.discourse.group/
