### ISSUE TITLE
Enable Travis-CI for automatic checking

### ISSUE THREAD

**Issue by GegznaV** [mixOmicsTeam/mixOmics#32]
Please, enable continuous integration service, such as [Travis CI](https://en.wikipedia.org/wiki/Travis_CI) (website: https://travis-ci.org), to carry out free automatic checking for **mixOmics**. In this way, you could know if, e.g., a new pull request breaks the functionality of the package or everything is OK.

The quickest way to enable Travis CI is to use function `usethis::use_travis()` (link to [**usethis**](https://usethis.r-lib.org/)) in the project of **mixOmics**. This function will create necessary setup files and will open websites, where you will have to sign in.

I cannot enable this service, as I am not in the "mixOmicsTeam".

**Comment by aljabadi** [comment]
Thanks for the suggestions. In the new developing version, Travis and CodeCov (plus support for MultiAssayExperiment datasets) are being implemented so stay tuned. However, it is pointless to activate them before the version passes full-scale preliminary checks.

Meanwhile, you can indeed contribute to mixOmics (or any other package really) by [forking the repository](https://help.github.com/en/articles/fork-a-repo), making your suggested changes, and submitting a [pull request](https://help.github.com/en/articles/creating-a-pull-request). This is much more efficient and if you already know how to implement the feature that you want, you will not have to go through all the details of explaining your ideas to developers and can simply implement it and submit a pull request (which we will appreciate a lot). After merging, you will automatically be acknowledged as a [contributor](https://github.com/mixOmicsTeam/mixOmics/graphs/contributors). Please refer to our [guidelines](https://github.com/mixOmicsTeam/mixOmics/blob/master/README.md#contributions) for more information. Hope this helps.

**Comment by aljabadi** [comment]
Additionally, if you wish to build/check the package locally, have a look at Hadley's [guidelines](http://r-pkgs.had.co.nz/package.html) (especially on `.Rbuildignore`). Also, for `devtools::check`, if you get errors in examples simply follow [this](https://stackoverflow.com/questions/17158049/avoid-checking-examples-for-r-package-building-using-devtools).

**Comment by aljabadi** [comment]
b0c6031c4b06173e29c1d718187b531119c93555 (bioc-release) and 50048969143461caf74c1cf7979170d23400912a (bioc-devel) close this. See [build reports](https://travis-ci.org/mixOmicsTeam/mixOmics/branches).
