### ISSUE TITLE
Enable Codecov service

### ISSUE THREAD

**Issue by GegznaV** [mixOmicsTeam/mixOmics#33]
After Travis CI is enabled (#32), please also enable [code coverage](https://en.wikipedia.org/wiki/Code_coverage) service, such as [Codecov](https://codecov.io/). It shows which lines of the package's code is covered by unit tests. So it helps to identify possible issues in functionality of a package.

The simplest way to enable is to use function `usethis::use_coverage("codecov")` after Travis CI is enabled.

About Codecov for R ([link](https://github.com/codecov/example-r)).

**Comment by aljabadi** [comment]
thanks for this reminder which was recently finalised in the package workflow.
