### ISSUE TITLE
Sudden check-error in DepecheR, because of some linux-chenge to your sPLS-DA function

### ISSUE THREAD

**Issue by jtheorell** [mixOmicsTeam/mixOmics#46]
Click the "Preview"  tab above to see this in HTML ^^^

By submitting this issue/request, I confirm that:

1. I have checked that I have the latest version installed, as described [here](https://github.com/mixOmicsTeam/mixOmics/tree/RELEASE_3_9#installation).

2. I have searched the [live NEWS file](https://github.com/mixOmicsTeam/mixOmics/blob/devel/NEWS.md) to see if it has been fixed in `devel` already. If so, I tried the latest `devel` version

3. I am aware that for analysis help I can refer to [Discourse](https://mixomics-users.discourse.group/) to see if my question is already answered or to submit a new one.

4. I am aware that if I get certain behaviour only using my data and not mixOmics datasets, it is best to send a fully confidential email with the code and (possibly a subset of) the data that reproduce the error to the following email (changing `[at]` and `[dot]` to `@` and `.`): mixomics[at]math[dot]univ-toulouse[dot]fr

**Thanks! Please delete the instructions above and fill in the items below:**

**Describe the bug**
Dear maintainers, 
I am the maintainer of DepecheR, that imports the sPLSDA function from mixOmics. Yesterday, I suddenly got a notice from the automatic build reports, that an check-error had happened on the Malbec1 test platform on BioConductor. See the build report here: 
http://bioconductor.org/checkResults/3.10/bioc-LATEST/DepecheR/
It still works for merida1 and tokay1, and as I run mac myself, I will struggle to reproduce the problem locally. I hope this is due to some new feature, and that it is an easy fix for you, because I very much like using the sPLS-DA function in its current form!
Best regards
Jakob Theorell

**Expected behavior**
See the test results for the merida1 and tokay1 runs. 

**Screenshots**

**[`Minimal reproducible example`](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example), preferably using the fantastic [`reprex` package](https://github.com/tidyverse/reprex):**
See the test module in the DepecheR package. 

**Output of sessionInfo()**:
```
sessionInfo()
```

**Comment by aljabadi** [comment]
Hi @jtheorell ,

It looks like the issue has been fixed in the build report. Please let me know if you run into further problems.

**Comment by jtheorell** [comment]
Hi @ajabadi, 
Yes, truly! I normally wait a few build reports with writing, but as it is in the middle of the next release build, I thought it was worth mentioning to you immediately. Thanks for your time!
