### ISSUE TITLE
Export logratio.transformed data

### ISSUE THREAD

**Issue by jjandshi** [mixOmicsTeam/mixOmics#47]
Click the "Preview"  tab above to see this in HTML ^^^

By submitting this issue/request, I confirm that:

1. I have checked that I have the latest version installed, as described [here](https://github.com/mixOmicsTeam/mixOmics/tree/RELEASE_3_9#installation).

2. I have searched the [live NEWS file](https://github.com/mixOmicsTeam/mixOmics/blob/devel/NEWS.md) to see if it has been fixed in `devel` already. If so, I tried the latest `devel` version

3. I am aware that for analysis help I can refer to [Discourse](https://mixomics-users.discourse.group/) to see if my question is already answered or to submit a new one.

4. I am aware that if I get certain behaviour only using my data and not mixOmics datasets, it is best to send a fully confidential email with the code and (possibly a subset of) the data that reproduce the error to the following email (changing `[at]` and `[dot]` to `@` and `.`): mixomics[at]math[dot]univ-toulouse[dot]fr

**Thanks! Please delete the instructions above and fill in the items below:**

**Describe the bug**

**Expected behavior**

**Screenshots**

**[`Minimal reproducible example`](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example), preferably using the fantastic [`reprex` package](https://github.com/tidyverse/reprex):**

**Output of sessionInfo()**:
```
sessionInfo()
```

**Comment by jjandshi** [comment]
Counts <- read.csv("counts_comTaxa.csv",row.names = 1, header = TRUE)
Counts_clr <- logratio.transfo(Counts, logratio = "CLR", offset = 0)
write.csv(CLR,'Clr_transfmd_counts.csv')
Error in as.data.frame.default(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors) : 
  cannot coerce class ‘"clr"’ to a data.frame

Could you please help me out?  It is ideal to generate the file with both original row name and header plus transformed data. Thanks,

**Comment by aljabadi** [comment]
Hi @jjandshi ,

I have no issue using mixOmics data so difficult to say what is actually happening since I don't have access to your data:
```
library(mixOmics)
data(diverse.16S)
CLR = logratio.transfo(X = diverse.16S$data.TSS, logratio = 'CLR')
write.csv(CLR,'Clr_transfmd_counts.csv')
```
So it does not look like a `mixOmics` issue, but a file write tweak.

Please try the following and see if it works:

```
library(mixOmics)
Counts <- read.csv("counts_comTaxa.csv",row.names = 1, header = TRUE)
Counts_clr <- logratio.transfo(Counts, logratio = "CLR", offset = 0)
class(CLR) <- "matrix"
write.csv(CLR,'Clr_transfmd_counts.csv')
```
If it does not, run the following and paste here what you get:

```
sum(!is.numeric(colMeans(CLR)))
head(CLR[,!is.numeric(colMeans(CLR))])
```

Hope it helps.

**Comment by smdabdoub** [comment]
I just ran into this issue as well. Does mixOmics depend on having objects of class 'clr'? It seems odd to have to change the class of a variable to use it for downstream applications. Especially something as widely applicable as a data transform.

**Comment by aljabadi** [comment]
Hi @smdabdoub, 

Can you please describe with a reproducible example what issue you are facing now and what you wish to be able to do? 

Best,

Al

**Comment by smdabdoub** [comment]
Hi @aljabadi 

The main issue is that the logratio.transfo function takes as input a matrix, and returns a matrix, but with the internal class changed to 'cls'. This makes it difficult to use in downstream pipelines without first changing the class back to 'matrix'.

For example, I would like to use the CLR transformed data with the MOFA2 library, but first I need to use the pivot_longer function in tidyr.
```
library(mixOmics)
library(tidyverse)

data(diverse.16S)
CLR = logratio.transfo(X = diverse.16S$data.TSS, logratio = 'CLR')

write_csv(CLR,'Clr_transfmd_counts.csv')
Error in write_delim(x, file, delim = ",", na = na, append = append, col_names = col_names,  : 
  is.data.frame(x) is not TRUE

df <- as.data.frame(CLR)
Error in as.data.frame.default(CLR) : 
  cannot coerce class ‘"clr"’ to a data.frame

tb <- tibble(CLR)
```
The last line does not cause an error, but inspecting `tb` shows that it is a table of 162x1. So only the first column was pulled into the tibble.

I can of course change the class, but the question is, why does the transform function change the class of the return variable when it is essentially just a label change, but one that breaks usage with other libraries.

Thanks,
Shareef

**Comment by kdbchau** [comment]
I am having the same issue - I wanted to preprocess my data and run CLR transformation on it. But now I can't use any of my downstream analysis because I can't convert it back into a data frame.
