### ISSUE TITLE
installing trouble

### ISSUE THREAD

**Issue by EKG2019** [mixOmicsTeam/mixOmics#53]
I would like to install mixomics but many error messages occured in particular as : 
The downloaded source packages are in
	‘C:\Users\xx\AppData\Local\Temp\RtmpEHj6U3\downloaded_packages’
Warning messages:
1: In install.packages(...) :
  installation of package ‘mixOmics’ had non-zero exit status
2: In install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  installation of package ‘emmeans’ had non-zero exit status
3: In install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  installation of package ‘rmarkdown’ had non-zero exit status

I tried to manually install emmeans and rmarkdown but another message occured 👍 
> install.packages("C:/Users/Emmanuelle Kesse/Desktop/tempo/rmarkdown_1.18.tar.gz", repos = NULL, type = "source")
Installing package into ‘C:/Users/Emmanuelle Kesse/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'rmarkdown' ...
** package 'rmarkdown' correctement décompressé et sommes MD5 vérifiées
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Erreur fatale : impossible d'ouvrir le fichier 'C:\Users\Emmanuelle' : No such file or directory

ERROR: lazy loading failed for package 'rmarkdown'
* removing 'C:/Users/xx/Documents/R/win-library/3.6/rmarkdown'
* restoring previous 'C:/Users/Exxx/Documents/R/win-library/3.6/rmarkdown'
Warning in install.packages :
  installation of package ‘C:/Users/xx/Desktop/tempo/rmarkdown_1.18.tar.gz’ had non-zero exit status
Could you help me?
>

**Comment by aljabadi** [comment]
Hi,

Can you please change your user folder name from `Emmanuelle Kesse` to `Emmanuelle_Kesse` (or any other name without space) and re-try.

Let me know how it goes.

**Comment by aljabadi** [comment]
I take it that your problem was resolved. Please do get back to us if further installation issues arise.
