### ISSUE TITLE
cim heatmap values 

### ISSUE THREAD

**Issue by just-greg** [mixOmicsTeam/mixOmics#54]
Hi mixOmics team,

Firstly, thank very much for curating / distributing the package. It's really useful and the graphics are spot on.

I'm particularly fond of the clustered image heatmaps but I have noticed one issue - perhaps you could suggest out a workaround or point out any thing I've missed. When using 'cim' to illustrate correlations between features and samples from a centered log ratio transformed feature table I get a bizarre scale for the colour key. (see below).

_Where 'combine_otu' is a log2 transformed, normalised feature table and 'Y_clin' is a character string defining subject class:_
`combine.plsda = plsda(X = t(combine_otu), Y_clin, ncomp = 3, logratio = 'CLR')`
`heat = cim(combine.splsda, cluster = "both", transpose = T, center = T)` 

Produces a 'cim' plot where the colour key scales from -2.61 to 2.61. 

I'm assuming this is due to the arbitrary scaling value produced by the log ratio transformed data but would make much more sense if I could rescale this to between -1 and 1.

I can see no way to perform this rescaling within the 'cim' function call so tried to rescale the splsda matrix myself using the 'scales' package:
`combine.splsda$X = rescale(combine.splsda$X, to = c(-1, 1))`
Producing the error:
`Error in UseMethod("rescale") : 
  no applicable method for 'rescale' applied to an object of class "clr"` 

So I tried to coerce the matrix to a data frame to allow me to use rescale:
`splsda.mat = as.matrix(combine.splsda$X)`
`splsda.mat = as.data.frame(splsda.mat)`
Which also produced an error:
`Error in as.data.frame.default(splsda.mat) : cannot coerce class "clr" to a data.frame`

Any help would be massively appreciated!

Many thanks,
Greg

**Comment by aljabadi** [comment]
Hi @just-greg,
Glad to know you find mixOmics helpful!
Are you using the latest version and still getting this behaviour?
Best,
Al

**Comment by just-greg** [comment]
Hi @ajabadi.
I'm running version 6.8.5. Are there plans for an update where rescaling the plsda matrix is an option?
Cheers,
Greg

**Comment by aljabadi** [comment]
Hi @just-greg,

I believe if you update to the latest version as instructed [here](https://github.com/mixOmicsTeam/mixOmics#installation) the `cim` problem should be resolved as this is a fixed bug.

As for the `plsda`, can you please elaborate a bit? Currently, the matrices are centered and there is a `scale` argument to standardise the columns. What type of rescaling you have in mind?
Best,
Al
