### ISSUE TITLE
plotIndiv(..., ind.names=FALSE) Warning: Removed N rows containing missing values (geom_point)

### ISSUE THREAD

**Issue by aljabadi** [mixOmicsTeam/mixOmics#59]
After upgrading to R 3.6.3, while the following works (with `ind.names=TRUE)`::

```r
    data(nutrimouse)
    X <- nutrimouse$lipid
    Y <- nutrimouse$gene
    nutri.res <- rcc(X, Y, ncomp = 3, lambda1 = 0.064, lambda2 = 0.008)
    
    plotIndiv(nutri.res,  group = nutrimouse$genotype, ind.names = TRUE, legend = TRUE)
```
![image](https://user-images.githubusercontent.com/28503057/76481201-ff3e4680-6464-11ea-9802-b68ba1f7ad48.png)

The following does not (with `ind.names=FALSE)`:

```r
    plotIndiv(nutri.res, group = nutrimouse$genotype, ind.names = FALSE, legend = TRUE)
```
> Warning messages:
> 1: Removed 40 rows containing missing values (geom_point). 
> 2: Removed 40 rows containing missing values (geom_point). 
![image](https://user-images.githubusercontent.com/28503057/76481289-37458980-6465-11ea-8531-0cf3541f4bea.png)

**Comment by guidohooiveld** [comment]
Just wanted to let you know that I faced this problem as well, and triggered by [this](https://mixomics-users.discourse.group/t/warning-message-for-missing-values-during-plotindiv-for-pca/158) recent discussion I updated `mixOmics` to the latest dev version ( v6.11.10). Problem was indeed solved.
G

**Comment by aljabadi** [comment]
Hi @guidohooiveld,
That's great. Thanks for your feedback.
I just merged the changes to master to push to bioC.

**Comment by aljabadi** [comment]
Resolved in https://github.com/mixOmicsTeam/mixOmics/commit/7d6ab529c128ec11f14398f6e37810489c6794c3

**Comment by marknormanread** [comment]
I'm afraid I'm having this exact same problem, and have updated to mixOmics v 6.13.19, and the problem is persisting. I've checked a previous version of my own code where all worked well, and that too is now experiencing this same issue.
