### ISSUE TITLE
Include verbose argument to tune.rcc

### ISSUE THREAD

**Issue by jonas-hag** [mixOmicsTeam/mixOmics#6]
Dear mixOmics team,

it would be great if the `tune.rcc` functions includes a verbose argument to turn off the automatic printing of the lambda values / CV-score. If wanted, I'm happy to provide a pull request.

Thanks
Jonas

**Comment by frohart** [comment]
Hi Jonas,

Thanks for opening the issue.
I commented out the lambda values/CV-score instead of adding an argument, they're already stored in the output so I think it's enough :)

commit d7c3fec
