### ISSUE TITLE
plotIndiv error

### ISSUE THREAD

**Issue by chongchunwie** [mixOmicsTeam/mixOmics#60]
Hi, I am running mixOmics using R v3.6.2. I was trying to plot the PLSDA plot using plotIndiv. I realised that when I set ind.names = FALSE, the symbol for the score plot disappeared. 

The following error message was given:

Warning messages:
1: Removed 16 rows containing missing values (geom_point). 
2: Removed 16 rows containing missing values (geom_point). 

I am using the example given in the tutorial. The same script was working fine before I update my R and re-installed all packages (including ggplot2). 

Thank you.

**Comment by aljabadi** [comment]
Hi, this issue is a duplicate of #59. Please install the latest devel version to resolve the issue. As a side note, when R is updated it should be ensured that BiocManager is also updated accordingly, which will automatically install the devel version of mixOmics.
