### ISSUE TITLE
Error when all-NAs present for a class in get.contrib.df

### ISSUE THREAD

**Issue by rronen** [mixOmicsTeam/mixOmics#62]
Running DIABLO analysis with a factor response variable (4 classes). If in a given block, one of the classes has all NA for any of the selected variables, there is an error coming from the following part of `get.contrib.df` :

```
which.contrib[k, 1:nlevels(Y)] = (method.group[[k]]) == get(contrib)((method.group[[k]]))
```

Adding `na.rm=TRUE` seems to help:
```
which.contrib[k, 1:nlevels(Y)] = (method.group[[k]]) == get(contrib)((method.group[[k]]), na.rm=TRUE)
```

**Comment by aljabadi** [comment]
Hi @rronen,

Thanks for reporting the issue and the suggestion. Can you please also provide a reproducible example that triggers this behaviour? This will be helpful for the purpose of unit tests.
Thanks,
Al
