### ISSUE TITLE
Error in tune.block.splsda() when using fixed test.keepX over two or more blocks

### ISSUE THREAD

**Issue by rronen** [mixOmicsTeam/mixOmics#63]
Hi MixOmics team, 

Thanks again for making this great package. 

I am running into errors while tuning block.splsda, which crop up consistently when my `test.keepX` list has entries of length=1 mixed in with entries of length >1. 

E.g., 
```
test.keepX <- list('ft1'=c(10), 'ft2'=c(10), ....., 'ft10'=c(10,20,30), 'ft11'=c(10))
```

This is important as I have many data dimensions and cannot afford to apply an actual grid search in all dimensions (therefore I set specific single values for some dimensions but would like to run the grid search in other dimensions). The call I am using is below. I cannot provide a full example with data, unfortunately. Any help here would be much appreciated. 

I should also point out my data has NAs.
 
```
tune.res <- mixOmics::tune.block.splsda(
      X=data, Y=Y, ncomp=2, 
      test.keepX=test.keepX, design=design,
      validation='Mfold', folds=10, nrepeat=1,
      cpus=1, dist='centroids.dist',
      scale=TRUE, init='svd',
      near.zero.var=FALSE # when setting this to TRUE I get different errors, but that's for another `Issue`
  )
```

The error:
```
Error in checkForRemoteErrors(val) : one node produced an error: 'names' attribute [11] must be the same length as the vector [2]
```
Removing the `cpus` argument I get a slightly more specific error:
```
Error in names(iter) <- names(A) : 
  'names' attribute [11] must be the same length as the vector [2]
```

UPDATE: I've verified I also get this error using data that has no NAs at all. 

If I then set e.g. `test.keepX$ft10 <- c(10)` in the above list, it goes through successfully (this is a trivial case of course; also runs where `test.keepX` entries all had e.g. length=2 completed successfully). I hope this is enough. Let me know if I can answer any questions. 

On a related note, it seems that `0` is not a valid value in the `test.keepX` lists? I.e. include an option in the grid to exclude the omic altogether. Feel free to ignore this part if it's something obvious I am not aware of and not related to the issue above.

**Output of sessionInfo()**:
```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reshape2_1.4.3  mixOmics_6.8.5  ggplot2_3.2.1   lattice_0.20-38 MASS_7.3-51.4  

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2         RSpectra_0.15-0    pillar_1.4.2       compiler_3.6.1     RColorBrewer_1.1-2 plyr_1.8.4        
 [7] tools_3.6.1        zeallot_0.1.0      tibble_2.1.3       lifecycle_0.1.0    gtable_0.3.0       pkgconfig_2.0.2   
[13] rlang_0.4.0        Matrix_1.2-17      igraph_1.2.4.1     rstudioapi_0.10    parallel_3.6.1     gridExtra_2.3     
[19] withr_2.1.2        dplyr_0.8.3        stringr_1.4.0      vctrs_0.2.0        grid_3.6.1         tidyselect_0.2.5  
[25] glue_1.3.1         ellipse_0.4.1      R6_2.4.0           snow_0.4-3         rARPACK_0.11-0     purrr_0.3.2       
[31] tidyr_1.0.0        corpcor_1.6.9      magrittr_1.5       ellipsis_0.2.0.1   scales_1.0.0       backports_1.1.4   
[37] matrixStats_0.55.0 assertthat_0.2.1   colorspace_1.4-1   stringi_1.4.3      lazyeval_0.2.2     munsell_0.5.0     
[43] crayon_1.3.4  
```

**Comment by aljabadi** [comment]
Hi @rronen,

Thanks for using mixOmics.

Currently, it is only possible to tailor the `test.keepX` grid to individual blocks but not to individual components. Therefore, `test.keepX`  will apply to all components.

However, using `already.tested.X` you can specify the optimal number of features to keep on, say, the first component, and only tune for the rest of the components. Following is an example:

``` r
suppressMessages(library(mixOmics))
data("breast.TCGA")
## data
data <-  list(
    mrna = breast.TCGA$data.train$mrna,
    mirna = breast.TCGA$data.train$mirna,
    protein = breast.TCGA$data.train$protein
)

## we want to fix the keepX for the first 2 componets
## individually for each block
already.tested.X <- list(mrna = c(5, 10), mirna = c(8, 20), protein = c(4, 8))
## and tune on the 3rd and 4th, the grid will be applied for every
## remaining components
test.keepX = list(mrna = c(10, 15), mirna = c(5, 10), protein = c(2, 8))

## design matrix
design = matrix(1, ncol = length(data), nrow = length(data),
dimnames = list(names(data), names(data)))
diag(design) =  0

## tune
tune = tune.block.splsda(
    X = data,
    Y = breast.TCGA$data.train$subtype,
    ncomp = 4,
    test.keepX = test.keepX,
    already.tested.X = already.tested.X,
    design = design,
    nrepeat = 2,
    folds = 2
)

## The first 2 components have used the given keepX across all blocks
tune$choice.keepX
#> $mrna
#> [1]  5 10 10 15
#> 
#> $mirna
#> [1]  8 20 10 10
#> 
#> $protein
#> [1] 4 8 2 2
```

<sup>Created on 2020-04-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

It is important to ensure that both `test.keepX` and `already.test.X` are named lists with the same name as blocks, and for which each element is a vector of positive integers, i.e. it cannot contain 0, although it can be a single value.

Please let us know if you have further questions.

**Comment by rronen** [comment]
Hi @ajabadi,

Thanks  so much for your reply! 

I unfortunately am not sure if that helps in this case. I am not looking to tailor `test.keepX` to individual components, and am happy to keep tuning as I am across all model components. 

I am however getting errors during the call to `tune.block.splsda()` which appear to be somehow relate to the content of `test.keepX`. I do not perfectly understand what is causing the issues but have noticed that it does not happen if my `test.keepX` have similar length lists. 

I.e., 
```R
# this or similar, seems to work
test.keepX = list(mrna = c(10, 15), mirna = c(5, 10), protein = c(2, 8))

# this or similar also works (yes, I know it's trivial)
test.keepX = list(mrna = c(10), mirna = c(5), protein = c(2))

# However, this often fails with errors similar to the above
test.keepX = list(mrna = c(10), mirna = c(5), protein = c(2, 8))
```

This may not be adding much information, but this only happens to me on datasets with many data dimensions (omics), i.e. I've never had the issue on a case like the above with just 3 omics but get it regularly on datasets that have ~10 or ~15 omics. 

Unfortunately, this is precisely where it matters most, as in those cases I cannot afford to have all entries in `test.keepX` with >1 elements (i.e. cannot train >= 2^15 models).
 
Any help here would be much appreciated.

**Comment by aljabadi** [comment]
Hi @rronen,

Thanks for clarifying the issue. It is indeed a rare case. I added a fix to that in the latest devel which should take care of the issue.

Please let me know if you keep having problems.

**Comment by rronen** [comment]
Thanks so much @ajabadi ! 

I wonder - as I am working on putting together a reproducible pipeline I would if possible like to avoid being on the bleeding edge with latest devel version. 

How does `mixOmics` team work w.r.t. releases / when would you expect this fix might make it into the version which I would get via e.g. `BiocManager::install()` ?

Thanks again!

**Comment by aljabadi** [comment]
You're welcome.
The _hot_  fixes are committed to the release versions and minor fixes are made available using `BiocManager::install('mixOmics', version = 'devel')` after testing so that there's less chance of making the release version unstable.

Please feel free to reach out if you have any further problems.

**Comment by rronen** [comment]
Thanks so much @ajabadi. 

I can confirm the latest github `devel` version resolves the issue for me. 

What is the appropriate way to know when this has made it into the `Bioconductor` release version? I ask because I now have the following in my docker build:
```R
devtools::install_github('mixOmicsTeam/mixOmics', ref='devel')
```
and ideally would like revert as soon as possible to the following:
```R
BiocManager::install('mixOmics')
```

Thank you!
Roy

**Comment by aljabadi** [comment]
Hi @rronen,

Glad to hear that.

The changes should be in effect in the new release as of April 29th.
It is already pushed to the latest [BioC release version](http://bioconductor.org/packages/3.11/bioc/html/mixOmics.html).

Best,

Al
