### ISSUE TITLE
circosPlot: add similarity matrix as Value output

### ISSUE THREAD

**Issue by mixOmicsTeam** [mixOmicsTeam/mixOmics#67]
https://github.com/mixOmicsTeam/mixOmics/blob/d6a44ab8901be925232f886d6ab640775c8d8771/R/circosPlot.R#L55

I propose we create a $simMat output to make it explicit we can export the similarity matrix. Currently:
```
nutrimouse.sgccda <- wrapper.sgccda(X=data,
Y = Y,
design = design,
keepX = list(gene=c(10,10), lipid=c(15,15)),
ncomp = 2,
scheme = "horst")
test = circosPlot(nutrimouse.sgccda, cutoff = 0.7, ncol.legend = 2, size.legend = 1.1)
test
```
outputs the matrix directly but the user needs to know they have to store the object. 
Proposes:
- A test$simMat output
- Updating  Roxygen to indicate this is a possible option.

**Comment by aljabadi** [comment]
With Roxygen, the return values are declared in @return directive (@export is for exporting the function which is not used for internals) and it is already included: https://github.com/mixOmicsTeam/mixOmics/blob/master/R/circosPlot.R#L30#L32. It needs a bit of modification which I'll see into.
