### ISSUE TITLE
Restore default graphic parameters in image.tune.rcc

### ISSUE THREAD

**Issue by jonas-hag** [mixOmicsTeam/mixOmics#7]
Dear mixOmics team,

it would be great if you could implement the automatic restoration of the default graphic parameters after the usage of `image.tune.rcc` (for example as recommended in `help(par)`. Then one could avoid using `par(mfrow=c(1,1))` manually after plotting the tunig results. If wanted, I'm happy to provide a pull request.

Thanks
Jonas

**Comment by frohart** [comment]
Hi Jonas,

It should work now!

commit ad3211d
