### ISSUE TITLE
Error in tune.block.splsda

### ISSUE THREAD

**Issue by rronen** [mixOmicsTeam/mixOmics#72]
Dear mixOmics Team, @ajabadi,

Running into an error during `tune.block.splsda`
```
Error in apply(test.keepA[, 1:length(X)], 1, function(x) paste(x, collapse = "_")) : 
  dim(X) must have a positive length
```

Seems like it might be coming from
https://github.com/mixOmicsTeam/mixOmics/blob/e7e25c07021d2e9a05b83e0f9f51360e48ffd2a5/R/MCV.block.splsda.R#L506

Not sure if this makes sense in the broader context of this part of the code but the error implies that perhaps `length(X) = 1` here, in which case maybe adding `drop=FALSE` would help? E.g., 
```R
keepA.names = apply(test.keepA[,1:length(X),drop=FALSE],1,function(x) ...
```

Getting this with current github stable from BioC, i.e. `6.13.11`. 

I'll just add that this seems to be somehow dependent on the predictors matrices. E.g., arbitrarily sampling down to 5% of the columns from each predictors omic matrix seems to prevent the problem (but giving a significantly less useful model). 

As always , your help and / or guidance is much appreciated.

**Comment by rronen** [comment]
One more note: if it is of any help on my local laptop environment which uses `6.11.35` I do not get the error when running with the same inputs.

(The issue is from running inside a docker container which gets periodically rebuilt and is needed for running on large inputs using a cluster)

**Comment by aljabadi** [comment]
Hi @rronen ,

Thanks for reporting this.

I can see that you mentioned `length(X) == 1`. Is `block.splsda` being called with only one block in X?

Best,

Al

**Comment by rronen** [comment]
Hi @ajabadi, no the input data has 3 blocks.

**Comment by aljabadi** [comment]
Hi @rronen,
I added what you suggested but I'm unable to test whether it fixes your issue. Can you please install the devel version and let me know.

Best,

Al

**Comment by rronen** [comment]
Thank you @ajabadi , that was helpful. I have installed devel from github (6.13.13) and now the `tune.block.splsda` call is completing successfully. 

However (with the same data), I now get an error during `perf` call:

```R
perf.diablo <- mixOmics::perf(sgccda.res,
                              validation='Mfold',
                              folds=folds,
                              nrepeat=10,
                              dist='centroids.dist',
                              cpus=4)
```

gives:
```R
Error in unserialize(node$con) : error reading from connection
```

If I reduce to `cpus=1` in order to get more informative error, the problem goes away and `perf` completes. Not sure what to make of that. 

It is important to have the ability for multiprocessing as this needs to run many times. 

Is there perhaps a possibility that something related to multi-processing was changed recently? 

Thank you as always for the prompt help.

**Comment by aljabadi** [comment]
Hi @rronen,

Glad to hear the former problem was resolved.

About the `perf` error, are you running the parallel code on a Windows machine? We did make some changes recently to use an enhanced backend for Windows which could have caused this.

Best,

Al

**Comment by rronen** [comment]
Hi @ajabadi ,

This was inside a  container running linux (built from base `r-base:3.6.0`); any ideas that might help to debug or understand the issue welcome (for now I've set things to run with `cores=1` but this is of course quite limiting). Let me know any additional info that might be helpful.

Best,
Roy

**Comment by aljabadi** [comment]
Hi @rronen,

You can install the version before the specific update to parallel processing using 
```r
BiocManager::install('mixOmicsTeam/mixOmics@d9a6aeae257102cd62f29f8fb32e412e6893c54c')
```
If this resolves the issue it could be because of https://github.com/mixOmicsTeam/mixOmics/commit/fb151cd7bc4fde3501beea8cb3199b5969310137.

Otherwise, can you please update to the latest R, try again and let us know. The dependencies are compatible with the latest R version and we need to narrow down.

Best,

Al

**Comment by rronen** [comment]
Hi @ajabadi,

I've updated to R 4.0.0 and installed `devel` from `github` (got version `mixOmics_6.13.13.tar.gz`) and:

1) It runs cleanly with `cpus=1` but if I use e.g. `cpus=4` I now get:
```
Error in apply(test.keepA[, seq_along(X), drop = FALSE], 1, function(x) paste(x,  : 
  dim(X) must have a positive length
```

Is it possibly related to one of my blocks being small ? (3 variables, and the grid for that block has only `c(3)`, this is a bit of a degenerate case but important for us to have the ability to handle it.)

2) I've noticed that I am no longer able to get the exact same result on the same input data, even when using `set.seed(123)` and `cpus=1`. This is very important for reproducibility. 

Thank you,
Roy

**Comment by aljabadi** [comment]
Hi @rronen,

I can look into it if there is a reproducible example. [You can click on this text to send us an email](mailto:mixomics@math.univ-toulouse.fr) with the code and (preferably minimal) data.
Alternatively, you can right-click on the above text and choose ‘Copy Email Address’.

Regarding the reproducibility with parallel `perf`, it is possible to pass a hidden `seed` argument to it which should take care of that. Note that it would only be reproducible when using the same number of `cpus`.

Hope it helps,

Al

**Comment by rronen** [comment]
Thanks so much @ajabadi. I will put together a (hopefully small) example and send it your way.

Thanks for the tip regarding `seed` in `perf`. I have in fact also been seeing the same issue with `tune.block.splsda`, will the same (i.e., hidden `seed`) work there as well? 

Thank you,
Roy

**Comment by aljabadi** [comment]
Hi @rronen, 

My pleasure.

I added a similar feature to `tune.block.splsda` but strangely on my machine I would get reproducible results regardless of seed. Not sure if it's a local issue as on the cloud the behavior is different.
Can you please install the latest `devel`, run the following, and let me know if you get different objects in first case, and identical objects in the second case?

```r

tune_please <- function(cpus = 1, folds = 3, seed = NULL) {
    library(mixOmics)
    data("breast.TCGA")
    data = list(
        mrna = breast.TCGA$data.train$mrna,
        mirna = breast.TCGA$data.train$mirna,
        protein = breast.TCGA$data.train$protein
    )
    design = matrix(
        1,
        ncol = length(data),
        nrow = length(data),
        dimnames = list(names(data), names(data))
    )
    diag(design) =  0
    ncomp <- 2
    nrep <- 3
    test.keepX = list(
        mrna = c(10, 20),
        mirna = c(20, 30),
        protein = c(3, 6)
    )
    
    tune.block.splsda(
        X = data,
        Y = breast.TCGA$data.train$subtype,
        ncomp = ncomp,
        test.keepX = test.keepX,
        design = design,
        folds = folds,
        nrepeat = nrep,
        cpus = cpus, 
        seed = seed)
}

stopifnot(packageVersion('mixOmics') > package_version('6.13.13'))

tune1 <- tune_please(cpus = 2)
tune2 <- tune_please(cpus = 2)
identical(tune1, tune2)
#> ?TRUE/FALSE

tune3 <- tune_please(cpus = 2, seed = 10)
tune4 <- tune_please(cpus = 2, seed = 10)
identical(tune3, tune4)
#> ?TRUE/FALSE
```
