### ISSUE TITLE
rCC center and scale the data by default

### ISSUE THREAD

**Issue by mixOmicsTeam** [mixOmicsTeam/mixOmics#75]
https://github.com/mixOmicsTeam/mixOmics/blob/e7e25c07021d2e9a05b83e0f9f51360e48ffd2a5/R/rcc.R#L128

@ajabadi could you add an extra step here to center and scale the data directly inside the function? Let me know then and I'll sort out the manual (it should not make much difference in terms of outputs, even in the plotVar function, but should be the right thing to do 'theoretically').

**Comment by gnngeorge** [comment]
Hey @mixOmicsTeam, 
Did this eventually get added to rCC? 
I still don't see a way to center and scale the data inside this function.
