### ISSUE TITLE
Change var.names of plotVar() function to display results of pls() function

### ISSUE THREAD

**Issue by siArzt** [mixOmicsTeam/mixOmics#78]
Dear mixOmics Team,
There is a problem with the PlotVar() function in combination with the results of the pls() function. You cannot change the names of the variables by using an appropriate list and var.names, as shown in the example.

```
data(nutrimouse)

MyResult.pls <- pls(nutrimouse$gene , nutrimouse$lipid) 
plotVar(MyResult.pls)
```
![Rplot_names](https://user-images.githubusercontent.com/67557936/85956408-05a9ed00-b986-11ea-8eae-50eb695ebe62.png)

```
> dim(nutrimouse$gene)
[1]  40 120
> dim(nutrimouse$lipid)
[1] 40 21
> plotVar(MyResult.pls , var.names = list(1:120 , 1:21))
Error in ind.var.sel[[x]] : subscript out of bounds
```
Getting this with the version **6.12.1**

I hope the bug is not on my side and you can fix it.
Thank you very much!
siArzt

**Comment by aljabadi** [comment]
Thanks for reporting this issue and the reproducible example. 

It should be resolved in the devel version (> = 6.13.15). Please let me know if the issue persists.

Best,
Al
