### ISSUE TITLE
PLS-DA and sPLS-DA should be regression mode only

### ISSUE THREAD

**Issue by mixOmicsTeam** [mixOmicsTeam/mixOmics#79]
https://github.com/mixOmicsTeam/mixOmics/blob/e7e25c07021d2e9a05b83e0f9f51360e48ffd2a5/R/plsda.R#L80

To be cross-checked but not other modes should be provided but the default regression.

**Comment by aljabadi** [comment]
@mixOmicsTeam I can see that the results are almost equal but not exactly. 

```r
data(breast.tumors)
X <- breast.tumors$gene.exp
Y <- breast.tumors$sample$treatment

plsda1 <- plsda(X, Y, ncomp = 2, mode = 'regression')
plsda2 <- plsda(X, Y, ncomp = 2, mode = 'canonical')
plsda3 <- plsda(X, Y, ncomp = 2, mode = 'classic')

pl1 <- plotIndiv(plsda1)
pl2 <- plotIndiv(plsda2)
pl3 <- plotIndiv(plsda3)

testthat::expect_identical(pl1$df, pl2$df)
# Error: pl1$df not identical to pl2$df.
# Component “y”: Mean relative difference: 0.0005707618
testthat::expect_identical(pl1$df, pl3$df)
# Error: pl1$df not identical to pl3$df.
# Objects equal but not identical
```

Additionally, the chosen mode is not altered through to `defl.select`. Not sure if I should assume it means all modes are valid for this case as well. You can also browse step by step in the example below and see that the `Y` (q = indY = 2) does go through the classic mode deflation:

```r
data(breast.tumors)
X <- breast.tumors$gene.exp
Y <- breast.tumors$sample$treatment

debugonce(mixOmics:::defl.select)
plsda3 <- plsda(X, Y, ncomp = 2, mode = 'classic')
```
I'm not sure what this implicates in a `DA` analysis though.

Let me know what you think, or if I got something wrong.
