### ISSUE TITLE
plot.tune.rcc instead of image.tune.rcc

### ISSUE THREAD

**Issue by jonas-hag** [mixOmicsTeam/mixOmics#8]
Dear mixOmics team,

it would be great to have the function `plot.tune.rcc` instead of `image.tune.rcc`. Then it is easier to plot objects with the class tune.rcc, and you already have similar functions for the classes tune.splsda and tune.block.splsda in your package. If wanted, I'm happy to provide a pull request.

Thanks
Jonas

**Comment by frohart** [comment]
Hi Jonas,

Thanks for all the issues, sorry for the delay (summer holidays).

I've added a new function plot.tune.rcc. I decided to leave image.tune.rcc in the package for now, but both do the same thing. We'll eventually discard that one.

Let me know if that answer your request!

commit 6b1226e
