### ISSUE TITLE
Change var.names of plotVar() function to display results of spca() function

### ISSUE THREAD

**Issue by siArzt** [mixOmicsTeam/mixOmics#81]
Dear mixOmics Team,
There is a problem with the PlotVar() function in combination with the results of the spca() function. You cannot change the names of the variables by using an appropriate list and var.names, as shown in the example.

```
library(mixOmics)
data(nutrimouse)

MyResult.spca <- spca(nutrimouse$gene , keepX = c(50 , 50)) 
plotVar(MyResult.spca )
```

![Rplot](https://user-images.githubusercontent.com/67557936/89651135-bed3df00-d8c3-11ea-8784-6006adafbf9b.png)

```
> dim(nutrimouse$gene)
[1]  40 120
plotVar(MyResult.spca , var.names = list(1: 120))
Error: var.names must be either a vector of length 1 or a list of 1 vector components of length 120 respectively.
```
Getting this with the version 6.13.21

I hope you can fix the bug.
Thank you very much!
Simon

**Comment by aljabadi** [comment]
Hi @siArzt,

Thanks for reporting this and the reproducible example. 

The issue should be resolved in the [latest devel version.](https://github.com/mixOmicsTeam/mixOmics#development-version) Please let me know if you continue to face any issues.

Best,

Al
