### ISSUE TITLE
Error in plotIndiv while reproducing sPLSDA - SRBCT and DIABLO - TCGA: Warning messages: 1: Removed 135 rows containing missing values (geom_point). The points are not plotted, also in my own data test did not work for DIABLO (same issue: plotIndiv)

### ISSUE THREAD

**Issue by yazbeck** [mixOmicsTeam/mixOmics#85]
Click the "Preview"  tab above to see this in HTML ^^^

By submitting this issue/request, I confirm that:

1. I am aware that for analysis help I can refer to [Discourse](https://mixomics-users.discourse.group/) to see if my question is already answered or to submit a new one.

2. I am aware that if I get certain behaviour only using my data and not mixOmics datasets, it is best to send a fully confidential email with the code and (possibly a subset of) the data that reproduce the error to the following email (changing `[at]` and `[dot]` to `@` and `.`): mixomics[at]math[dot]univ-toulouse[dot]fr

3. I have checked that I have the latest version installed, as described [here](https://github.com/mixOmicsTeam/mixOmics/tree/RELEASE_3_9#installation).

4. I have searched the [live NEWS file](https://github.com/mixOmicsTeam/mixOmics/blob/devel/NEWS.md) to see if it has been fixed in `devel` already. If so, I tried the latest `devel` version

**Thanks! Please delete the instructions above and fill in the items below:**

**Describe the issue**

**Expected behavior**

**Screenshots**

**[`Minimal reproducible example (if it is an issue)`](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example), preferably using the fantastic [`reprex` package](https://github.com/tidyverse/reprex):**

**Output of sessionInfo() (if it is an issue)**:
```
sessionInfo()
```

**Comment by aljabadi** [comment]
@yazbeck I think this is a duplicate of #59. Please [update to the latest GitHub/Bioconductor version](https://github.com/mixOmicsTeam/mixOmics#installation) and it should be resolved.
