### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by staci12** [mixOmicsTeam/mixOmics#89]
I have R version 4.0.2 for Windows

> install.packages("C:/Users/Staci Board/Desktop/mixOmics_6.3.2.tar.gz", repos=NULL, type="source")
Installing package into ‘C:/Users/Staci Board/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'mixOmics' ...
** package 'mixOmics' successfully unpacked and MD5 sums checked
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : there is no package called 'crosstalk'
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package 'mixOmics'
* removing 'C:/Users/Staci Board/Documents/R/win-library/3.6/mixOmics'
* restoring previous 'C:/Users/Staci Board/Documents/R/win-library/3.6/mixOmics'
Warning in install.packages :
  installation of package ‘C:/Users/STACIB~1/Desktop/mixOmics_6.3.2.tar.gz’ had non-zero exit status
>

**Comment by aljabadi** [comment]
As apparent from the error message, the issue is with one of the dependencies (`crosstalk`) and not `mixOmics` itself. I recommend you try to see why that would not install and submit an issue to them if the problem persists.
