### ISSUE TITLE
How to get variable importance from each class?

### ISSUE THREAD

**Issue by ozanfaw** [mixOmicsTeam/mixOmics#91]
when we perform this code, `plotLoadings(train.plsda, contrib = 'max', method = 'mean', comp = 1)` we will get contribution of the variables in comp 1, with the legend of each class. 

So, I need to know, in each class, what is the most important variable contribute to each comp(s).

**Comment by aljabadi** [comment]
Hi @ozanfaw ,

As you would have noticed in the issue template, please post the analysis-related questions to [Discourse](https://mixomics-users.discourse.group/) so others could also benefit from /contribute to discussions and we'd be happy to help. 

Best,

Al
