### ISSUE TITLE
Compatibility with R 4.0.2

### ISSUE THREAD

**Issue by K-Pimentel** [mixOmicsTeam/mixOmics#92]
Hi, 

I have a few colleagues who have been struggling to install mixOmics when using the most recent version of R (4.0.2) and the Bioconductor installation:
```{R}
## install BiocManager if not installed if (!requireNamespace("BiocManager", quietly = TRUE))     install.packages("BiocManager") 
## install mixOmics 
BiocManager::install('mixOmics')
```
Are you aware of this issue or is there a way to address it by using for example devTools()?

Thanks

**Comment by aljabadi** [comment]
Hi @K-Pimentel,

Currently, Bioconductor release and devel work with R 4.0.0 (http://bioconductor.org/install/). Have your colleagues tried installing the latest stable from GitHub? You can do so using 
```r
BiocManager::install("mixOmicsTeam/mixOmics")
```
Also, I recommend you ensure `BiocManager::valid()` returns `TRUE` before any installation. It might recommend some upgrades but I wouldn't worry about `packages too new` warnings if you are using R 4.0.2.

Please let me know if the issue persists.
Al

**Comment by aljabadi** [comment]
I take it that this issue has been resolved. Please re-open if otherwise.
