### ISSUE TITLE
Biplot warnings for PCA

### ISSUE THREAD

**Issue by mixOmicsTeam** [mixOmicsTeam/mixOmics#97]
https://github.com/mixOmicsTeam/mixOmics/blob/4d327b860a5532cd4997c47e970b813b4fe60fc0/R/biplot.R#L1

library(mixOmics)
#> Loading required package: MASS
#> Loading required package: lattice
#> Loading required package: ggplot2
#> 
#> Loaded mixOmics 6.13.56
#> Thank you for using mixOmics!
#> Tutorials: http://mixomics.org
#> Bookdown vignette: https://mixomicsteam.github.io/Bookdown
#> Questions, issues: Follow the prompts at http://mixomics.org/contact-us
#> Cite us:  citation('mixOmics')
data(multidrug)
X <- multidrug$ABC.trans
dim(X) # check dimension of data
#> [1] 60 48
pca.result <- pca(X, ncomp = 3, center = TRUE, scale = TRUE)
# pca.result  # list possible outputs
cell.line = as.factor(multidrug$cell.line$Class)
biplot(pca.result, group = cell.line)
#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

#> Warning in abs(x) >= cutoff: longer object length is not a multiple of shorter
#> object length

reprex::reprex(si = TRUE)
#> No input provided and clipboard is not available.
#> Rendering reprex...
Created on 2020-09-29 by the reprex package (v0.3.0)

Session info

**Comment by Max-Bladen** [comment]
Warnings cannot be reproduced using the above code or any other. Even if `cutoff = c(0.99, 0.99)`, the above warning is not raised, instead error is raised by `ggplot` (as would be expected). Hence, closing the issue as it seems a fix was implemented some time in the past
